# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'truyen' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for truyen
  pod 'OneSignal', '~> 1.13.3'

  target 'truyen-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'truyenTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'truyen-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for truyen-tvOS

  target 'truyen-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
