module.exports = {
  PAGE_SIZE: 10,
  NETWORK_ERROR: "NETWORK_ERROR",
  STATUS_CONFIRM: -1,
  STATUS_CONFIRM_SHIPPING: -11,
  STATUS_SHIPPING: 0,
  STATUS_CANCEL_USER: -12,
  STATUS_CANCEL: -2,
  STATUS_FINISH: 1
};
